# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmasterareamodel',
            name='ad_type',
            field=models.CharField(choices=[('NORM', 'NORMAL'), ('ADUL', 'ADULT')], default='NORM', max_length=4, verbose_name='ad_type'),
        ),
        migrations.AlterField(
            model_name='pagedetail',
            name='today_share_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='today share counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AlterField(
            model_name='pagedetail',
            name='today_social_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='today social counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AlterField(
            model_name='pagedetail',
            name='total_share_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='total share counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AlterField(
            model_name='pagedetail',
            name='total_social_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='total social counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AlterField(
            model_name='webmasterareamodel',
            name='today_share_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='today share counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AlterField(
            model_name='webmasterareamodel',
            name='today_social_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='today social counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AlterField(
            model_name='webmasterareamodel',
            name='total_share_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='total share counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AlterField(
            model_name='webmasterareamodel',
            name='total_social_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='total social counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
    ]
