# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster_area', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webmasterareamodel',
            name='share_today_counter',
        ),
        migrations.RemoveField(
            model_name='webmasterareamodel',
            name='share_total_counter',
        ),
        migrations.AddField(
            model_name='webmasterareamodel',
            name='today_share_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='today share counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AddField(
            model_name='webmasterareamodel',
            name='today_social_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='today social counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AddField(
            model_name='webmasterareamodel',
            name='total_share_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='total share counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AddField(
            model_name='webmasterareamodel',
            name='total_social_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='total social counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
    ]
