# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedetail',
            name='today_share_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='today share counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AlterField(
            model_name='pagedetail',
            name='today_social_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='today social counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AlterField(
            model_name='pagedetail',
            name='total_share_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='total share counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AlterField(
            model_name='pagedetail',
            name='total_social_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='total social counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AlterField(
            model_name='webmasterareamodel',
            name='buttons_constructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webmaster_area', to='buttons_constructor.ButtonsConstructorModel', verbose_name='related_buttons_constructor'),
        ),
        migrations.AlterField(
            model_name='webmasterareamodel',
            name='today_share_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='today share counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AlterField(
            model_name='webmasterareamodel',
            name='today_social_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='today social counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AlterField(
            model_name='webmasterareamodel',
            name='total_share_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='total share counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AlterField(
            model_name='webmasterareamodel',
            name='total_social_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='total social counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
    ]
