# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster_area', '0002_auto_20160228_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagedetail',
            name='page_share_counter',
        ),
        migrations.RemoveField(
            model_name='pagedetail',
            name='page_social_traffic',
        ),
        migrations.AddField(
            model_name='pagedetail',
            name='today_share_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='today share counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AddField(
            model_name='pagedetail',
            name='today_social_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='today social counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AddField(
            model_name='pagedetail',
            name='total_share_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='total share counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AddField(
            model_name='pagedetail',
            name='total_social_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='total social counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
    ]
