# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster_area', '0002_auto_20160316_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
        ),
    ]
