# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster_area', '0003_areacategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmasterareamodel',
            name='ad_type',
            field=models.CharField(choices=[('NORM', 'Нормальный'), ('ADUL', 'Для взрослых')], default='NORM', max_length=4, verbose_name='ad_type'),
        ),
    ]
