# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster_area', '0004_auto_20160317_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmasterareamodel',
            name='area_category',
            field=models.CharField(default='Авто/Мото,IT/Computers', max_length=600, verbose_name='area_category'),
        ),
    ]
