# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster_area', '0005_webmasterareamodel_area_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webmasterareamodel',
            name='today_share_counter',
        ),
        migrations.RemoveField(
            model_name='webmasterareamodel',
            name='today_social_counter',
        ),
        migrations.RemoveField(
            model_name='webmasterareamodel',
            name='total_share_counter',
        ),
        migrations.RemoveField(
            model_name='webmasterareamodel',
            name='total_social_counter',
        ),
        migrations.AlterField(
            model_name='webmasterareamodel',
            name='area_category',
            field=models.CharField(default='Авто/Мото,IT/Computers,DNB', max_length=600, verbose_name='area_category'),
        ),
    ]
