# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster_area', '0007_auto_20160410_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedetail',
            name='title',
            field=models.CharField(default='', max_length=512, verbose_name='page title'),
        ),
    ]
