# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster_area', '0008_auto_20160415_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='areatoday',
            name='today_click_counter',
            field=models.IntegerField(default=0, verbose_name='today click counter'),
        ),
        migrations.AddField(
            model_name='areatoday',
            name='today_money',
            field=models.FloatField(default=0.0, verbose_name='today money in rub'),
        ),
        migrations.AddField(
            model_name='areatoday',
            name='today_show_counter',
            field=models.IntegerField(default=0, verbose_name='today show counter'),
        ),
        migrations.AlterField(
            model_name='webmasterareamodel',
            name='area_category',
            field=models.CharField(default='Авто/Мото,IT/Computers,DNB,Кино / Видео', max_length=600, verbose_name='area_category'),
        ),
    ]
