# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-11 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster_area', '0010_auto_20160610_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetoday',
            name='default_today_click_counter',
            field=models.IntegerField(default=0, verbose_name='default today click counter'),
        ),
        migrations.AddField(
            model_name='pagetoday',
            name='default_today_money',
            field=models.FloatField(default=0.0, verbose_name='default today money in rub'),
        ),
        migrations.AddField(
            model_name='pagetoday',
            name='default_today_share_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='default today share counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
        migrations.AddField(
            model_name='pagetoday',
            name='default_today_show_counter',
            field=models.IntegerField(default=0, verbose_name='default today show counter'),
        ),
        migrations.AddField(
            model_name='pagetoday',
            name='default_today_social_counter',
            field=models.CharField(default='0,0,0,0,0,0,0,0', max_length=300, verbose_name='default today social counter(vk,fb,tw,od,gp,ma,li,lj)'),
        ),
    ]
