# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster_area', '0011_auto_20160611_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default=' ', max_length=200, verbose_name='header')),
                ('text', models.TextField(blank=True, default=' ', verbose_name='text')),
            ],
        ),
    ]
