# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.CharField(max_length=2, verbose_name='shortcut for network')),
                ('url', models.URLField(default='', verbose_name='url for network')),
                ('img_bd_pos', models.CharField(max_length=400, verbose_name='img background position')),
            ],
        ),
    ]
