# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons_constructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonsconstructormodel',
            name='mobile_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buttonsconstructormodel',
            name='social_networks',
            field=models.CharField(default='vk,fb,tw,od,gp,ma,li,lj', max_length=300),
        ),
    ]
