# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons_constructor', '0003_auto_20160224_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetworks',
            name='img',
            field=models.URLField(blank=True, default='', verbose_name='img_url'),
        ),
        migrations.AlterField(
            model_name='buttonsconstructormodel',
            name='social_networks',
            field=models.CharField(default='', max_length=300),
        ),
    ]
