# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buttons_constructor', '0004_buttonsconstructormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonsconstructormodel',
            name='btns_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buttons_constructor', to='buttons_constructor.BtnsImages', verbose_name='related btns images'),
        ),
        migrations.AlterField(
            model_name='buttonsconstructormodel',
            name='social_networks',
            field=models.CharField(default='vk,fb,tw,od,gp,ma,li,lj', max_length=300),
        ),
    ]
