# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons_constructor', '0005_auto_20160225_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworks',
            name='img',
            field=models.URLField(default='', verbose_name='img_url'),
        ),
    ]
