# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons_constructor', '0005_auto_20160314_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonsconstructormodel',
            name='name_constructor',
            field=models.CharField(default='Default constructor', max_length=50, verbose_name='name_constructor'),
        ),
    ]
