# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 11:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buttons_constructor', '0006_auto_20160317_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('BUY', 'Купить'), ('SHO', 'Выходящая реклама')], default='BUY', max_length=3)),
                ('ad_allow', models.CharField(choices=[('TIZ', 'Тизеры'), ('MED', 'Медийная')], default='MED', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertBtnImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name image')),
                ('path', models.CharField(max_length=200, verbose_name='path to image')),
            ],
        ),
        migrations.AlterField(
            model_name='buttonsconstructormodel',
            name='btns_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buttons_constructor', to='buttons_constructor.BtnsImages', verbose_name='related btns images'),
        ),
        migrations.AddField(
            model_name='advert',
            name='btn_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advert', to='buttons_constructor.AdvertBtnImage', verbose_name='related advert btn image'),
        ),
        migrations.AddField(
            model_name='advert',
            name='buttons_constructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advert', to='buttons_constructor.ButtonsConstructorModel', verbose_name='related buttons constructor'),
        ),
        migrations.AddField(
            model_name='advert',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advert', to=settings.AUTH_USER_MODEL, verbose_name='related user'),
        ),
    ]
