# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_webmaster', '0017_chat_to_user_pk'),
        ('buttons_constructor', '0007_auto_20160513_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='user',
        ),
        migrations.AddField(
            model_name='advert',
            name='cabinet_webmaster',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advert', to='cabinet_webmaster.CabinetWebmasterModel', verbose_name='related cabinet webmaster'),
        ),
        migrations.AddField(
            model_name='advert',
            name='click_counter',
            field=models.IntegerField(default=0, verbose_name='click counter'),
        ),
        migrations.AddField(
            model_name='advert',
            name='show_counter',
            field=models.IntegerField(default=0, verbose_name='show counter'),
        ),
    ]
