# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons_constructor', '0008_auto_20160513_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='ad_type',
            field=models.CharField(choices=[('BUY', 'Купить'), ('SHO', 'Выходящая реклама')], default='SHO', max_length=3),
        ),
    ]
