# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buttons_constructor', '0009_auto_20160514_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='buttons_constructor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advert', to='buttons_constructor.ButtonsConstructorModel', verbose_name='related buttons constructor'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='cabinet_webmaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advert', to='cabinet_webmaster.CabinetWebmasterModel', verbose_name='related cabinet webmaster'),
        ),
    ]
