# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons_constructor', '0010_auto_20160515_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertbtnimage',
            name='bg_position',
            field=models.CharField(default='background-position: -368px 0px;', max_length=100, verbose_name='background position'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='ad_allow',
            field=models.CharField(choices=[('TI1', '1 Блок'), ('TI2', '2 Блока'), ('TI3', '3 Блока'), ('ME1', '240x400'), ('ME2', '728x90'), ('ME3', '300x250')], default='ME1', max_length=3),
        ),
        migrations.AlterField(
            model_name='buttonsconstructormodel',
            name='size_buttons',
            field=models.CharField(choices=[('BIG', 'Big'), ('MED', 'Medium'), ('SML', 'Small')], default='BIG', max_length=3),
        ),
    ]
