# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons_constructor', '0011_auto_20160518_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertbtnimage',
            name='bg_position_med',
            field=models.CharField(default='background-position: -280px 0px;', max_length=100, verbose_name='background position medium'),
        ),
        migrations.AddField(
            model_name='advertbtnimage',
            name='bg_position_sml',
            field=models.CharField(default='background-position: -190px 0px;', max_length=100, verbose_name='background position small'),
        ),
        migrations.AddField(
            model_name='socialnetworks',
            name='img_bd_pos_med',
            field=models.CharField(default='background-position: 0px 0px;', max_length=400, verbose_name='img background position med'),
        ),
        migrations.AddField(
            model_name='socialnetworks',
            name='img_bd_pos_sml',
            field=models.CharField(default='background-position: 0px 0px;', max_length=400, verbose_name='img background position sml'),
        ),
        migrations.AlterField(
            model_name='advertbtnimage',
            name='bg_position',
            field=models.CharField(default='background-position: -370px 0px;', max_length=100, verbose_name='background position big'),
        ),
        migrations.AlterField(
            model_name='buttonsconstructormodel',
            name='social_networks',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='socialnetworks',
            name='img_bd_pos',
            field=models.CharField(default='background-position: 0px 0px;', max_length=400, verbose_name='img background position big'),
        ),
    ]
