# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons_constructor', '0013_auto_20160522_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='money_counter',
            field=models.FloatField(default=0.0, verbose_name='earned money in rub'),
        ),
    ]
