# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_webmaster', '0002_auto_20160304_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetwebmastermodel',
            name='money',
            field=models.FloatField(default=0.0, verbose_name='money in rub'),
        ),
    ]
