# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_webmaster', '0005_auto_20160309_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetwebmastermodel',
            name='wmr',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='wmr'),
        ),
    ]
