# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 20:31
from __future__ import unicode_literals

import cabinet_webmaster.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinet_webmaster', '0006_auto_20160309_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user_pk', models.IntegerField(verbose_name='to_user_pk')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='date_create')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='date_update')),
                ('department', models.CharField(choices=[('BIL', 'Billing'), ('SUP', 'Support')], default='BIL', max_length=3)),
                ('status', models.CharField(choices=[('CLO', 'CLOSE'), ('ACT', 'ACTIVE'), ('ANS', 'ANSWERED')], default='ACT', max_length=3)),
                ('header', models.CharField(blank=True, default='', max_length=100, verbose_name='message_header')),
                ('text', models.TextField(default='', verbose_name='message_text')),
                ('upload_file', models.FileField(upload_to=cabinet_webmaster.models.generate_filename)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat', to=settings.AUTH_USER_MODEL, verbose_name='related_user')),
            ],
        ),
    ]
