# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinet_webmaster', '0009_auto_20160427_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='from_name')),
                ('text', models.TextField(default='', verbose_name='message_text')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='date_update')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message', to='cabinet_webmaster.Chat', verbose_name='related_chat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_message', to=settings.AUTH_USER_MODEL, verbose_name='related_user')),
            ],
        ),
    ]
