# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_webmaster', '0010_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='is_staff',
            field=models.BooleanField(default=False, editable=False, verbose_name='is_staff'),
        ),
    ]
