# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 09:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinet_webmaster', '0012_chatmessagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagefile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_message_file', to=settings.AUTH_USER_MODEL, verbose_name='related_user'),
        ),
    ]
