# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_webmaster', '0013_chatmessagefile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_create'),
        ),
    ]
