# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_webmaster', '0014_auto_20160427_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is_staff'),
        ),
    ]
