# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_webmaster', '0015_auto_20160509_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='chatmessagefile',
            name='file_name',
            field=models.CharField(blank=True, default='file', max_length=100, verbose_name='file_name'),
        ),
    ]
