# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-29 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinet_webmaster', '0017_chat_to_user_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wmr', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='user_wmr')),
                ('money', models.FloatField(default=0.0, verbose_name='money in rub')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date_create')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='date_update')),
                ('status', models.CharField(choices=[('WAI', 'wait'), ('ACE', 'accept'), ('DEC', 'decline')], default='WAI', max_length=3)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance', to=settings.AUTH_USER_MODEL, verbose_name='related_user')),
            ],
        ),
    ]
